version: '1'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    links:
#      - db:db
#    ports:
#      - "8015:8015"
#    environment:
#      - DB_URL=postgresql+psycopg2://postgres:ratestask@db:5432/rates-service
#    depends_on:
#      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ratestask
      POSTGRES_DB: rates-service
